spring:
  application:
    name: mysite07

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  main:
    allow-bean-definition-overriding: true

  aop:
    auto: true
    proxy-target-class: true

  mvc:
    static-path-pattern: /assets/**

  web:
    resources:
      static-locations: 
        - classpath:assets/
        - file:///Users/dayeon/Desktop/mysite-uploads/

  servlet:
    multipart:
      enabled: true
      max-file-size: 10485760
      max-request-size: 104857600
      file-size-threshold: 5242880

  messages:
    basename: messages/message
    encoding: utf-8

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.19:3306/webdb
    username: webdb
    password: webdb
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

mybatis:
  config-location: classpath:mybatis/configuration.xml

server:
  port: 8080
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: true
    path: /error

logging:
  config: classpath:logback.xml
