spring:
  application:
    name: mysite06

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  aop:
    auto: true
    proxy-target-class: true

  main:
    allow-bean-definition-overriding: true

#Server configuration
server:
  port: 8080
  servlet:
    context-path: /mysite06
